name: Publish Package to Python Package Index

on:
  push:
    paths-ignore:
    - .github/**
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: 🔨 Checkout
        uses: actions/checkout@v3

      - name: 🔨 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🔨 Setup Dependencies
        run: |
          python -m pip install poetry
          poetry install
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: 📦 Build
        run: poetry build

      - name: 🎉 Publish
        run: poetry publish
